// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using POS.Infrastructure.Database;

#nullable disable

namespace POS.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120031536_Add_Product_ProductVariant_Brand_Tables")]
    partial class Add_Product_ProductVariant_Brand_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("POS.Domain.Brands.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.ToTable("brands", "public");
                });

            modelBuilder.Entity("POS.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<bool>("IsVatable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vatable");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "POS.Domain.Products.Product.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "POS.Domain.Products.Product.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_products_brand_id");

                    b.ToTable("products", "public");
                });

            modelBuilder.Entity("POS.Domain.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsVatable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vatable");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.ComplexProperty<Dictionary<string, object>>("Price", "POS.Domain.Products.ProductVariant.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Size", "POS.Domain.Products.ProductVariant.Size#PackageSize", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("package_size_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("package_size_value");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnitOfMeasure", "POS.Domain.Products.ProductVariant.UnitOfMeasure#UnitOfMeasure", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("ItemsPerCase")
                                .HasColumnType("integer")
                                .HasColumnName("unit_of_measure_items_per_case");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("unit_of_measure_type");
                        });

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_variants_product_id");

                    b.ToTable("product_variants", "public");
                });

            modelBuilder.Entity("POS.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "public");
                });

            modelBuilder.Entity("POS.Domain.Brands.Brand", b =>
                {
                    b.OwnsOne("POS.Domain.Shared.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("BrandId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("citext")
                                .HasColumnName("name");

                            b1.HasKey("BrandId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_brands_name");

                            b1.ToTable("brands", "public");

                            b1.WithOwner()
                                .HasForeignKey("BrandId")
                                .HasConstraintName("fk_brands_brands_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("POS.Domain.Products.Product", b =>
                {
                    b.HasOne("POS.Domain.Brands.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_brands_brand_id");

                    b.OwnsOne("POS.Domain.Products.ProductCode", "ProductCode", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("product_code");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_products_product_code");

                            b1.ToTable("products", "public");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.Navigation("ProductCode")
                        .IsRequired();
                });

            modelBuilder.Entity("POS.Domain.Products.ProductVariant", b =>
                {
                    b.HasOne("POS.Domain.Products.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products_product_id");

                    b.OwnsOne("POS.Domain.Products.Barcode", "Barcode", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("barcode");

                            b1.HasKey("ProductVariantId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_product_variants_barcode");

                            b1.ToTable("product_variants", "public");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId")
                                .HasConstraintName("fk_product_variants_product_variants_id");
                        });

                    b.OwnsOne("POS.Domain.Products.Sku", "Sku", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("sku");

                            b1.HasKey("ProductVariantId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_product_variants_sku");

                            b1.ToTable("product_variants", "public");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId")
                                .HasConstraintName("fk_product_variants_product_variants_id");
                        });

                    b.Navigation("Barcode")
                        .IsRequired();

                    b.Navigation("Sku")
                        .IsRequired();
                });

            modelBuilder.Entity("POS.Domain.Products.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
